Added Nextcloud bookmarks app.
nextcloud/Android-SingleSignOn pull request #524
Opened 2023-02-19 09:16 UTC by dasbiswajit

Added Nextcloud bookmarks app.

2023-02-19 09:24 UTC, stefan-niedermann requested changes

2023-02-19 09:24 UTC, stefan-niedermann commented on README.md
> +  - [API](https://nextcloud-bookmarks.readthedocs.io/en/latest/)
With `API` is not the server part of the API meant but the part of the client app that connects to the REST endpoints - in your case this is here: `https://gitlab.com/bisada/OCBookmarks/-/blob/master/app/src/main/java/org/schabi/ocbookmarks/REST/OCBookmarksRestConnector.java`

2023-02-19 13:34 UTC, stefan-niedermann approved these changes

2023-02-21 06:46 UTC, tobiasKaminsky approved these changes

2023-02-21 06:46 UTC, merged